//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsNet48Basics
{
    public partial class EmployeeList
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkCreate;
        protected global::System.Web.UI.WebControls.HyperLink lnkHome;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.GridView gvEmployees;
    }
}
