@BasicAuthWorkshop_HostAddress = http://localhost:5101

GET {{BasicAuthWorkshop_HostAddress}}/
Accept: application/json

###

GET {{BasicAuthWorkshop_HostAddress}}/public
Accept: application/json

###

# analyst:Passw0rd! -> YW5hbHlzdDpQYXNzdzByZCE=
GET {{BasicAuthWorkshop_HostAddress}}/secure/profile
Authorization: Basic YW5hbHlzdDpQYXNzdzByZCE=
Accept: application/json

###

# admin:Adm1nPass! -> YWRtaW46QWRtMW5QYXNzIQ==
GET {{BasicAuthWorkshop_HostAddress}}/secure/admin
Authorization: Basic YWRtaW46QWRtMW5QYXNzIQ==
Accept: application/json

###
